### ISSUE TITLE
Application error

### ISSUE THREAD

**Issue by urob** [Eun/MoveToDesktop#12]
Hi,

I started using the 1.2 release version with Windows 10 64bit. When starting the program I get an application error saying that "The application was unable to start correctly (0xc000007b). Click OK to close the application." Then when pressing ok, the program seems to work fine, but only on non-system related windows (even when run as administrator).

Sorry to have no more specific info, but do you have any idea what goes wrong?

Thanks

**Comment by Eun** [comment]
Hey, did you installed Visual C++ Redistributable for Visual Studio 2015, x86 and x64?

**Comment by urob** [comment]
Ah, I also need it when using the compiled version? It seems be running fine for most part without...

**Comment by Eun** [comment]
Yeah, you need it even when running. 
It might be that x86 or x64 applications don't display the menu item if you have not installed the redistributable.

Note to myself:
Check if we can remove dependencies to the redistributable.

**Comment by urob** [comment]
I tried it and it all works fine now. Thanks a lot for such a useful tool!

**Comment by Eun** [comment]
Fixed in 106e34033349a8267c13b74a86b47c213f4d542f
