### ISSUE TITLE
Switch Desktop After Move is not working

### ISSUE THREAD

**Issue by Gonzo0324** [Eun/MoveToDesktop#13]
Hello, the SwitchDesktop after Move is not working for me.  I've put the ini file in my appdata/local folder, does it need to be in the roaming folder instead?

I have the ini file set to SwitchDesktopAfterMove=1, but the desktop stays the same after I move the application.

**Comment by Eun** [comment]
It should be in to wherever `%AppData%` resolves to.  
Enter `%AppData%` in your Explorer Addressbar and look where it takes you.

**Comment by Gonzo0324** [comment]
Ok, that works now.  I was pretty sure I had tried it in both locations but it's now working.
