### ISSUE TITLE
[feature request ] Move to in taskbar right click

### ISSUE THREAD

**Issue by ghost** [Eun/MoveToDesktop#2]
Any chance you can add this functionality to the right click on the program's icon on the taskbar

**Comment by Eun** [comment]
If you hold <kbd>Shift</kbd> and open the right click menu it will apear.

![untitled](https://cloud.githubusercontent.com/assets/796084/11936194/807999c6-a80c-11e5-9065-d146ddf8727f.png)

I check it out if it is possible to add the menuitem to the "normal" menu.

**Comment by froggercat** [comment]
Looks like this feature's been implemented. Can this issue be closed?
