### ISSUE TITLE
Windows 10 Anniversary Update support

### ISSUE THREAD

**Issue by joemck** [Eun/MoveToDesktop#20]
I was sad to see that the new Anniversary Update completely breaks MoveToDesktop. No hotkeys, no desktop switching, no context menu items, on any programs at all. It's as if MoveToDesktop isn't running at all. It makes no difference if it's run as elevated or normally.

**Comment by treylon** [comment]
Got the same problems here.

**Comment by Eun** [comment]
Confirmed, needs investigation.

**Comment by Ciantic** [comment]
@Eun New MIDL_INTERFACE for the IVirtualDesktopManagerInternal is f31574d6-b682-4cdc-bd56-1827860abec6 [See my DLL for example](https://github.com/Ciantic/VirtualDesktopAccessor/blob/master/VirtualDesktopAccessor/Win10Desktops.h#L56)

**Comment by M3Rocket** [comment]
I actually am holding off the MS update (on 5 computers!) till MoveToDesktop is fixed to work with it. I have developed too much muscle memory, and rely on it's features quite a bit. :-(

**Comment by Ciantic** [comment]
@M3Rocket I updated my DLL to work with it, if you use AutoHotkey, you might want to try it: https://github.com/Ciantic/VirtualDesktopAccessor 

Moving a window also does not need to inject to the process memory anymore, so I have the safer way to do it.

**Comment by Eun** [comment]
Fix in d55414090a4e94d410433fc10fdb4db871c26f42

**Comment by Eun** [comment]
Release here https://github.com/Eun/MoveToDesktop/releases/tag/1.4
