### ISSUE TITLE
MoveToDesktop broken after windows 10 anniversary update?

### ISSUE THREAD

**Issue by kkuhle** [Eun/MoveToDesktop#22]
I can't seem to get it working after the update.

**Comment by Eun** [comment]
What have you tried?

**Comment by kkuhle** [comment]
Re-extracted after killing the movetodesktop processes and re-ran.  Still wasn't working (1.3).  Found the update here that you've added (1.4) seems to work properly after disabling it from being blocked in "smartscreen."  Seems to be working well again!  Thanks for your help!
