### ISSUE TITLE
Unable to use CTRL+WIN in the same hotkey

### ISSUE THREAD

**Issue by kkuhle** [Eun/MoveToDesktop#24]
I've been trying to set my move window to "SHIFT+CTRL+WIN+RIGHT/LEFT" but I see the error "Error on Registering Left-Hotkey (SHIFT+WIN+CTRL+LEFT)! ErrorCode:1409"

I assume this is because the native windows virtual desktop switching uses CTRL+WIN+RIGHT/LEFT, but I just wanted to see if there is a way around this as I'd like to use the same hotkey with shift added

**Comment by Eun** [comment]
There is no posiblity to override an existing windows hotkey.

**Comment by kkuhle** [comment]
I get that we can't override the hotkey, but I was hoping there was a way to add an additional key to the existing windows hotkey to active yours.  I get if that's not possible, just thought it might be.

**Comment by mzomparelli** [comment]
Actually, you can override built-in hotkeys (just about all of them) if you use a keyboard hook instead of the RegisterHotKey API. My app overrides many of them including the default CTRL+WIN+Arrow.

https://github.com/mzomparelli/zVirtualDesktop
