### ISSUE TITLE
Ability to specify the desktop the window is being moved to

### ISSUE THREAD

**Issue by Rudedog9d** [Eun/MoveToDesktop#25]
Feature request (Sorry, don't know how to tag it as such!):
On my XFCE system, I use `Super+F{n}` (Super is Windows key for those that don't know!) to switch desktop n - that is I `Super+F1` for desktop 1, `Super+F2` for desktop 2... 

I use `Super+1`, `Super+2` ect. to send a window to that desktop - any way you could implement something similiar? I really like being able to tell it what window to go to. I'll look into doing something like that myself, but my C isn't so good :)

-Brodie

**Comment by Eun** [comment]
#17
