### ISSUE TITLE
Bitdefender,F-Secure etc detect as 'Gen:Variant.Razy.90153'

### ISSUE THREAD

**Issue by kiuuik** [Eun/MoveToDesktop#26]
Here is a recent scan from [virustotal](https://virustotal.com/de/file/c2fce6ccfbfd1773b087ab3623d36c0c2b81b23fc35363822eaf6ace2061a3a1/analysis) - 12 out of 55 detect MoveToDesktop as malware.

IIrc the Bitdefender engine is licensed to many other AV vendors.

**Comment by Eun** [comment]
See what I can do.
#21

**Comment by kiuuik** [comment]
now it's down to 2 out of 54.
