### ISSUE TITLE
Build errors when rebuilding with VS2015 Enterprise

### ISSUE THREAD

**Issue by jmenashe** [Eun/MoveToDesktop#29]
I am getting the following errors when I attempt to build the entire solution using Visual Studio 2015 Enterprise Edition:

```
Severity    Code    Description Project File    Line    Suppression State
Error   MSB3073 The command "taskkill /f /fi "IMAGENAME eq MoveToDesktop*" /im *
:VCEnd" exited with code 1. MoveToDesktop   C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets  123 
Error   MSB3073 The command "taskkill /f /fi "IMAGENAME eq MoveToDesktop*" /im *
:VCEnd" exited with code 1. MoveToDesktop   C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets  123 
```

In the attached image below I have activated the first of these errors in order to highlight the source code. Both errors are generated from the same source.

![build_error](https://cloud.githubusercontent.com/assets/3631136/18190430/d0110d32-7077-11e6-86d2-0211780a4759.png)

**Comment by Eun** [comment]
You can simply remove that task, I have added it to kill existing MoveToDesktop instances

**Comment by jmenashe** [comment]
I figured that much, but I reported it because a newcomer should probably be able to build your solution without errors as a general rule.

Great project, by the way. Thanks!
