### ISSUE TITLE
[feature request] Add global Hotkeys to move one Desktop left or right

### ISSUE THREAD

**Issue by schierlm** [Eun/MoveToDesktop#3]
I really like your tool - it is faster than typing <kbd>Win</kbd>+<kbd>Tab</kbd> and then fiddling with the mouse (especially when you have many windows open and want two of them on a new desktop). Instead just press <kbd>Alt</kbd>+<kbd>Space</kbd> and move to the desired desktop :)

But I think it would be super useful to add two more global HotKeys (for example <kbd>Win</kbd>+<kbd>Shift</kbd>+<kbd>Left</kbd>/<kbd>Right</kbd>, or <kbd>Win</kbd>+<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Left</kbd>/<kbd>Right</kbd>) to move the currently focused window (if any) to the next or previous desktop (just like <kbd>Win</kbd>+<kbd>Ctrl</kbd>+<kbd>Left</kbd>/<kbd>Right</kbd> move between them).

Or if that is not possible, add some `&` to the context menu labels so I can do <kbd>Alt</kbd>+<kbd>Space</kbd>, <kbd>o</kbd>, <kbd>1</kbd> instead of using cursor keys :)

Thanks for consideration.

**Comment by Eun** [comment]
`&` is definitely possible, I will see what I can do on those hotkeys.

**Comment by schierlm** [comment]
I did not look at your code (so shame on me), but basically, I'd have one single process/thread in the system (that has a message loop) that uses [RegisterHotKey](https://msdn.microsoft.com/en-us/library/windows/desktop/ms646309%28v=vs.85%29.aspx) to register the hotkeys and on `WM_HOTKEY` message post a `WM_SYSCOMMAND` to the current Foreground window (so it appears to your hook library just like somebody used the system menu).

This assumes you are using a hook DLL for customizing the system menu (I don't know of any other method to do that, so shame on me if there is any).

**Comment by eleijonmarck** [comment]
Plus one for this also! Would be super awesome if there would be such a global hotkey. I am a newly graduate developing for .NET so I cannot help out as of now. :8ball:

**Comment by schierlm** [comment]
TIL that <kbd>Win</kbd>+<kbd>Shift</kbd>+<kbd>Right</kbd> can be used to push a window to the next monitor (if you have more than one) - so the variations with <kbd>Win</kbd>+<kbd>Ctrl</kbd>+<kbd>Shift</kbd>\+ would probably be the better ones

**Comment by anyong** [comment]
+1 for <kbd>Win</kbd>+<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Left/Right</kbd> to move between desktops!

The default for switching desktops is <kbd>Win</kbd>+<kbd>Ctrl</kbd>+<kbd>Left/Right</kbd>, so adding the <kbd>Shift</kbd> to move the current window makes sense.
