### ISSUE TITLE
Where exactly put .ini

### ISSUE THREAD

**Issue by lukaszadamski** [Eun/MoveToDesktop#33]
I would like to ask where exactly I should put MoveToDesktop.ini? 

I've put it in the c:\users(user name)\appdata folder. 

I am trying to get SwitchDesktopAfterMove activated but it is not working. Also which is the best way to restart the program? Just kill it in the Task Manager and restart?

**Comment by wesv** [comment]
You need to put the ini file inside of the %AppData% folder. To figure out where this is, you can open the command prompt and type "echo %AppData%". Put MoveToDesktop.ini in the folder specified. The folder should be something along the lines of "C:/Users/(user)/Roaming". And for restarting the app, I've found killing it in the Task Manager and reopening the .exe works.
