### ISSUE TITLE
Ini file not working

### ISSUE THREAD

**Issue by enumag** [Eun/MoveToDesktop#44]
I want to activate the `SwitchDesktopAfterMove` feature but the ini file doesn't seem to work for me.

I did the following:
- Downloaded MoveToDesktop.exe and put it into `C:\Users\Enumag\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\MoveToDesktop.exe` (to start it automatically).
- Downloaded [MoveToDesktop.ini](https://github.com/Eun/MoveToDesktop/blob/master/MoveToDesktop.ini) and put it to `C:\Users\Enumag\AppData\MoveToDesktop.ini`
- Changed the configuration to `SwitchDesktopAfterMove=1`.
- Restarted my PC to apply the configuration changes.

Unfortunately when I press Win+Alt+Left/Right the active window disappeares to the next desktop but the active desktop doesn't change until I press Win+Crtl+Left/Right.

Am I doing something wrong?

**Comment by mzomparelli** [comment]
Eun has created a great tool here. If you would like to try another similar utility that is easier to configure then check this out.

https://github.com/mzomparelli/zVirtualDesktop

**Comment by enumag** [comment]
Yeah your program does seem more user friendly - and more active since you're still working on it. Thanks.
