### ISSUE TITLE
Suggestion: Could you add MoveToDesktop to the Windows Store?

### ISSUE THREAD

**Issue by casaout** [Eun/MoveToDesktop#46]
It would be amazing to distribute MoveToDesktop as a utility app via Windows Store using the Desktop Conversion bridge (https://developer.microsoft.com/en-us/windows/bridges/desktop). Any thoughts?

**Comment by mzomparelli** [comment]
I don't think this is possible for desktop applications that need to work with windows that it does not own. I've been looking to see if my virtual desktop can be converted to Windows Store and it cannot be converted.

https://github.com/mzomparelli/zVirtualDesktop

**Comment by casaout** [comment]
ok, thanks for the info. This would have been great...
