### ISSUE TITLE
hey! is there a hotkey for the move to new desktop?

### ISSUE THREAD

**Issue by ieikhelberg** [Eun/MoveToDesktop#49]

**Comment by mzomparelli** [comment]
You can move windows by using WIN+ALT+Left/Right

Alternatively, you can try this app.
https://github.com/mzomparelli/zVirtualDesktop

**Comment by ieikhelberg** [comment]
@mzomparelli thank you, I'm tried it. But this app does not allow move windows to the NEW desktop.

**Comment by mzomparelli** [comment]
zVirtualDesktop will. If you try and move a window to a desktop that doesn't exist then it will create it for you. Try and let me know what you think.

**Comment by ieikhelberg** [comment]
@mzomparelli no, it's not what I need.

**Comment by ieikhelberg** [comment]
@mzomparelli for example: I have a several virtual desktops. On each of them one application is launched. When I open a new application on the desktop 1, I want to move it to a NEW DESKTOP, and not to the next one. Using hot keys.

**Comment by mzomparelli** [comment]
@ieikhelberg you can do this with zVD, but only if you know the number of your last desktop. For instance, if I have 3 desktops, then I could move a window from desktop 1 to desktop 4 using ALT+WIN+4. I could use CTRL+ALT+WIN+4 to move the window and navigate to desktop 4. I could easily add a hotkey action to move to a new desktop. In fact, I'm doing that right now.

**Comment by ieikhelberg** [comment]
@mzomparelli no, this is a bad way. I want to setup my trackpad for this hotkey.

**Comment by ieikhelberg** [comment]
@mzomparelli I'll be grateful to you, if you'll do it

**Comment by mzomparelli** [comment]
@ieikhelberg try getting a new zVD with the below link. I just compiled an update. Then setup a hotkey like this. If this doesn't work then tell me more about how you want the hotkey to work with the trackpad.

https://zomp.co/files.aspx?id=zvd

![image](https://user-images.githubusercontent.com/10564234/28501869-da136fa4-6faa-11e7-8db9-5a117c4daea0.png)

**Comment by mzomparelli** [comment]
@ieikhelberg  also check out DesktopView in zVD.

**Comment by ieikhelberg** [comment]
@mzomparelli  it is great! Thank you very much!
