### ISSUE TITLE
Keyboard shortcut confict

### ISSUE THREAD

**Issue by ycrichard** [Eun/MoveToDesktop#5]
Notice that <kbd>WIN</kbd>+<kbd>ALT</kbd>+<kbd>Left/Right</kbd> is also the default shortcut for forward and backward action (same as <kbd>ALT</kbd>+<kbd>Left/Right</kbd>).
In a browser or windows explorer with a history list, this does not work very well. Sometimes it send the current window to the next desktop, but most of the time it just perform a backward action. 
Any solutions?

**Comment by anyong** [comment]
<kbd>Win</kbd>+<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Left/Right</kbd> was suggested in issue #3. I don't think that conflicts with anything.

**Comment by Eun** [comment]
<kbd>Win</kbd>+<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Left/Right/Top/Bottom</kbd> is allready used, you can move the active window to the left, right, maximize or minimize.

<kbd>WIN</kbd>+<kbd>ALT</kbd>+<kbd>Left/Right</kbd> makes no trouble for me. Whether it is in Windows Explorer or Internet Explorer

**Comment by ycrichard** [comment]
I found out that <kbd>WIN</kbd>+<kbd>ALT</kbd>+<kbd>Left/Right</kbd> was buggy only when I assigned it to the logitech's mouse gesture. Otherwise, it's fine.
But maybe it is just my computer being strange, <kbd>Win</kbd>+<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Left/Right/Top/Bottom</kbd> will do the window snapping left or right. There is nothing to do with the multi-desktop, right?

**Comment by anyong** [comment]
Moving the Window to fill left/right half of screen or min/max for me is
Win + arrows. Win + Ctrl + Shift + arrows doesn't do anything for me on
Windows 10.

**Comment by cheuer** [comment]
How about making the shortcut configurable in the INI file?

It may also be a good idea to provide the INI file in the zip file with the release.

**Comment by OneRegisteredUser** [comment]
Has any more thought gone into this recently? I also think configurable via INI file is a good solution for everyone.

**Comment by mustanggb** [comment]
After a <kbd>Win</kbd>+<kbd>Tab</kbd> then <kbd>Alt</kbd>+<kbd>Left/Right</kbd> works as intended.
After a <kbd>Win</kbd> then <kbd>Alt</kbd>+<kbd>Left/Right</kbd> triggers MoveToDesktop actions, not good.

Also please add an ini option to disable hotkeys.

**Comment by Eun** [comment]
Guys could you try out the Prerelease 1.2 if all works it goes to release.
Thanks.
ab75722ff11aaad4917c7d26f4434aa5453a6050

**Comment by mustanggb** [comment]
Tested <kbd>Alt</kbd>+<kbd>Left/Right</kbd> mis-triggering as well as disabling by with an empty string, both worked perfectly!

Didn't test other hotkey combinations though.

**Comment by ycrichard** [comment]
I tested with another key combination, it works fine as long as is not already registered.
It is great that the original issue has also been fixed! No more mis-triggering of forward or backward action. Thanks for the update!

**Comment by Eun** [comment]
Great thanks.
https://github.com/Eun/MoveToDesktop/releases/tag/1.2
