### ISSUE TITLE
When the window moves to another desktop, the View should also change to that Desktop

### ISSUE THREAD

**Issue by panuganti** [Eun/MoveToDesktop#57]
When the window moves to another desktop, the View should also change to that Desktop.
Currently, it looks as if the current window just vanished.

Also, some quick transition animation would also be helpful.

**Comment by xan2622** [comment]
I worry about this "transition animation". Please add it if you want but as an togglable option. 
I would not want it to slow down my productivity. 

I like the idea to switch to the other Desktop after moving a window onto it.

**Comment by Eun** [comment]
There is a setting for that in the .ini file: `SwitchDesktopAfterMove`
