### ISSUE TITLE
[feature request] when moving app to another desktop also switch to that desktop

### ISSUE THREAD

**Issue by polyx** [Eun/MoveToDesktop#6]
When I move an app to another desktop I would like to also change to that desktop. Perhaps 2 different shortcuts, one for just move and one for move and change to that desktop.

**Comment by Eun** [comment]
Set `SwitchDesktopAfterMove=1` in the [MoveToDesktop.ini](https://raw.githubusercontent.com/Eun/MoveToDesktop/master/MoveToDesktop.ini) and save it into `%AppData%`

**Comment by polyx** [comment]
Thanks, didn't notice that there were an ini until I went to sources to add this feature myself :)
