### ISSUE TITLE
Awesome tools! And I am looking forward to "move to deaktop and follow"! 

### ISSUE THREAD

**Issue by Junpliu** [Eun/MoveToDesktop#61]
Thank you very much, Eun, for this wonderful tools!
It would be perfect if it adds the functionality of" moving to desktop and foolow view to the desktop"! 
Thank you very much for great contribution again!

**Comment by Eun** [comment]
There is an `SwitchDesktopAfterMove` option in the ini file

**Comment by Junpliu** [comment]
> There is an `SwitchDesktopAfterMove` option in the ini file

Oh, thank you so much! I found that. 
happy!
