### ISSUE TITLE
New desktop sometimes creates unwanted multiples

### ISSUE THREAD

**Issue by mustanggb** [Eun/MoveToDesktop#8]
I started with 3 desktops all created from the Windows task view pane, then did a "Move To > New Desktop" and ended up with 18 desktops, deleted most of them to reduce back to 4, did another "Move To > New Desktop" and ended up with 19 desktops, deleted even more this time going back to the original 3, did another "Move To > New Desktop" and this time ended up with 4 desktops as expected.

**Comment by mustanggb** [comment]
Just had the same thing happen when moving windows with hotkeys, tried to move a window right from desktop 1 to desktop 2, instead it created a new desktop 5 and moved it there instead.

**Comment by KaiStarkk** [comment]
Just had the same issue.

I have the latest version of both VC++ redist. and the tool was run with administrator privileges.

Note that this only happens for some windows. Explorer windows move around just fine - so far I've had this issue with Excel and Chrome windows.

**Comment by konnichimade** [comment]
I'm having the same issue as @akamustang. Using the hotkeys sometimes creates ~20 new desktops and moves the window to the last one.
