### ISSUE TITLE
Not working with insider build 14328

### ISSUE THREAD

**Issue by ycrichard** [Eun/MoveToDesktop#9]
I read that MS implements switching desktops with the touchpad in this build. So probably there are some other changes regarding to the multi-desktop API?

**Comment by Eun** [comment]
I probably check the api if the new Api is final.

**Comment by hansek** [comment]
I have evidently the same issue, because of after upgrading Windows to build 14342.1001 (few weeks ago) I'm unable to move windowsto other desktops :cry: :smile: 

Looking forward to next version!

Thanks for this tool.

**Comment by Eun** [comment]
#20
